---
- name: Testing andrewrothstein.tilt
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'tilt version'
      ansible.builtin.command: /usr/local/bin/tilt version
      changed_when: false
      register: tilt_test_output
    - name: Output of 'tilt version'
      ansible.builtin.debug:
        msg: '{{ tilt_test_output.stdout }}'
