---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/tilt version
    register: tilt_test_output
  - name: tilt version
    debug:
      msg: '{{ tilt_test_output.stdout }}'
