---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ tilt_exe }}
  ansible.builtin.stat:
    path: '{{ tilt_exe }}'
  changed_when: false
  register: tilt_binary
- name: Downloading and installing tilt
  when: not tilt_binary.stat.exists
  block:
    - name: Downloading {{ tilt_url }} to {{ tilt_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ tilt_url }}'
        dest: '{{ tilt_tmp_archive }}'
        mode: '644'
        checksum: '{{ tilt_checksum }}'
    - name: Mkdir {{ tilt_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ tilt_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchive {{ tilt_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ tilt_tmp_archive }}'
        dest: '{{ tilt_install_dir }}'
        creates: '{{ tilt_exe }}'
  always:
    - name: Rm {{ tilt_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ tilt_tmp_archive }}'
        state: absent
- name: Linking {{ tilt_link }} to {{ tilt_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ tilt_exe }}'
    dest: '{{ tilt_link }}'
    state: link
