---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ tilt_install_dir }}
  stat:
    path: '{{ tilt_install_dir }}'
  changed_when: false
  register: tilt_binary
- when: not tilt_binary.stat.exists
  block:
    - name: downloading {{ tilt_url }} to {{ tilt_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ tilt_url }}'
        dest: '{{ tilt_tmp_archive }}'
        mode: 0644
        checksum: '{{ tilt_checksum }}'
    - name: mkdir {{ tilt_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ tilt_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ tilt_tmp_archive }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ tilt_tmp_archive }}'
        dest: '{{ tilt_install_dir }}'
        creates: '{{ tilt_exe }}'
  always:
    - name: rm {{ tilt_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ tilt_tmp_archive }}'
        state: absent
- name: linking {{ tilt_link }} to {{ tilt_exe }}
  become: true
  become_user: root
  file:
    src: '{{ tilt_exe }}'
    dest: '{{ tilt_link }}'
    state: link
